# Site Settings
title: Shruti Raj
description: Documenting things
theme: jekyll-theme-cayman # Popular options: minimal, tactile, slate, hacker

# Social Links (Visible in some themes)
github_username: shrutiraj25
show_downloads: false

# Build Settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
